{% set name = "spyboat" %}
{% set version = "0.1.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 07a40fb2fbc58a48c6d1df737939fa131ee7ab8956b0f35b86c9373ac5dba2e9
  
build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python >=3.6
    - pip
    - flit-core >=2.3
  run:
    - python >=3.6
    - numpy >=1.18    
    - matplotlib-base >=3.1
    - scikit-image >=0.14.0
    - pyboat >=0.8.22

test:
  imports:
    - spyboat

about:
  home: https://github.com/tensionhead/spyboat
  license: GPL-3.0-or-later
  license_file: LICENSE
  summary: SpyBOAT - Spatial pyBOAT
  description: "Small pipeline for the time-frequency analysis of 3d image stacks. For details about the analysis strategy see pyBOAT documentation."
  dev_url: https://github.com/tensionhead/spyboat

extra:
  recipe-maintainers:
    - tensionhead
